[env:genericSTM32L051C8]
platform = ststm32
board = genericSTM32L051C8
framework = arduino

upload_protocol = serial

build_flags =
	-Os
	-D HAL_UART_MODULE_ENABLED

lib_deps =
	adafruit/Adafruit GFX Library @ ^1.12.5
	adafruit/Adafruit SSD1306 @ ^2.5.16
	rootshell/PS2Mouse
